version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/02_simpleroute"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "Asia/Seoul"
  - package-ecosystem: "npm"
      directory: "/03_props-state"
      schedule:
        interval: "weekly"
        day: "wednesday"
        timezone: "Asia/Seoul"
  - package-ecosystem: "npm"
      directory: "/05_proverb-to-title"
      schedule:
        interval: "weekly"
        day: "wednesday"
        timezone: "Asia/Seoul"
  - package-ecosystem: "npm"
      directory: "/06_weather-api"
      schedule:
        interval: "weekly"
        day: "wednesday"
        timezone: "Asia/Seoul"
  - package-ecosystem: "npm"
      directory: "/07_express-tryout"
      schedule:
        interval: "weekly"
        day: "wednesday"
        timezone: "Asia/Seoul"
