version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/0*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/1*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/2*"
    schedule:
      interval: "weekly"
      day: "wednesday"
      timezone: "Asia/Seoul"
    open-pull-requests-limit: 5
